### PR TITLE
fix: lables in figure

### PR DESCRIPTION
**Pull request by peppelinux**
This PR resolves https://github.com/openid/federation/issues/132

however, I have to report @selfissued, the term Final Metadata is often used within the draft.
Do we have to change it to Resolved Metadata for consistency?

### CODE REVIEW

**Comment by selfissued** [comment]
"Resolved Metadata" occurs 10 times and "Final Metadata" occurs 3 times - always in examples or figure <name> values.  So I think we should go with "Resolved Metadata" for consistency.

Can you update the PR to also change the other two occurrences of "Final Metadata" to "Resolved Metadata", @peppelinux?  Thanks!

**Comment by selfissued** [comment]
I noticed that this PR didn't update the asciiflow.com link above the example.  Should it have?

And should the link have a right parenthesis ")" at the end of it, or was that a typo?

**Comment by peppelinux** [comment]
@selfissued text aligned to Resolved Metadata

trailing ) is part of the url, not a typo

**Review by vdzhuvinov — APPROVED** [review]
Verified the two URLs for the figures - okay!

**Pull request merged**
